name: Build
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: anksalunkhe987/CodeReview
          ref: main
          token: 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
          path: ./
      
