name: Build
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: anksalunkhe987/CodeReview
          ref: v1.0
          token: ${{ secrets.CODEREVIEW }}
          path: ./
      
